cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_1
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_2
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_3
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_4
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_5
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_6
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_7
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_8
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_9
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_10
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_1
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_2
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_3
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_4
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_5
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_6
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_7
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_8
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_9
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_10
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_1
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_2
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_3
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_4
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_5
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_6
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_7
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_8
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_9
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_10
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_1
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_2
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_3
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_4
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_5
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_6
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_7
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_8
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_9
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_10
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_1
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_2
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_3
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_4
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_5
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_6
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_7
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_8
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_9
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_10
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_1
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_2
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_3
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_4
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_5
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_6
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_7
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_8
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_9
cp /home/soleary/BULLSHARKS/CLE_POPGEN/scr/idxstats.sh /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_10
