samtools flagstat	data/SEQ/CLE-2/CLE_2A-A01_Cleu_Ara001-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-A02_Cleu_Ara002-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-A03_Cleu_Ara003-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-A04_Cleu_Ara004-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-A05_Cleu_Ara005-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-A06_Cleu_Ara006-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-A07_Cleu_Ara007-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-A08_Cleu_Ara008-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-A09_Cleu_Ara009-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-A10_Cleu_Ara010-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-A11_Cleu_Dic001-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-A12_Cleu_Dic002-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-B01_Cleu_Dic003-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-B02_Cleu_Dic004-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-B03_Cleu_Dic005-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-B04_Cleu_Dic006-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-B05_Cleu_Dic007-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-B06_Cleu_Dic008-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-B07_Cleu_Dic009-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-B08_Cleu_Dic010-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-B09_Cleu_Lag001-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-B10_Cleu_Lag002-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-B11_Cleu_Mat001-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-B12_Cleu_Mat002-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-C01_Cleu_Mat003-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-C02_Cleu_Mat004-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-C03_Cleu_Mat005-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-C04_Cleu_Mat006-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-C05_Cleu_Mat007-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-C06_Cleu_Mat008-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-C07_Cleu_Ara010-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-C08_Cleu_Ara091-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-E01_Cleu_Sab001-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-E02_Cleu_Sab002-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-E03_Cleu_Sab003-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-E04_Cleu_Sab004-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-E05_Cleu_Sab005-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-E06_Cleu_Sab006-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-E07_Cleu_Sab007-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-E08_Cleu_Sab008-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-E09_Cleu_Sab009-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-E10_Cleu_Sab010-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-E11_Cleu_San001-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-E12_Cleu_San002-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-F01_Cleu_San003-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-F02_Cleu_San004-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-F03_Cleu_San005-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-F04_Cleu_San006-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-F05_Cleu_San007-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-F06_Cleu_San008-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-F07_Cleu_Ara019-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-F08_Cleu_Ara020-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-F09_Cleu_Ara021-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-F10_Cleu_Ara022-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-F11_Cleu_Ara023-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-F12_Cleu_Ara024-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-G01_Cleu_Ara025-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-G02_Cleu_Ara026-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-G03_Cleu_Ara027-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-G04_Cleu_Ara028-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-G05_Cleu_Ara029-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-G06_Cleu_Ara030-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-G07_Cleu_Dic013-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2A-G08_Cleu_Ara064-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-A01_Cleu_Ara091-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-A02_Cleu_Ara092-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-A03_Cleu_Ara093-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-A04_Cleu_Ara094-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-A05_Cleu_Ara095-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-A06_Cleu_Ara096-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-A07_Cleu_Ara097-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-A08_Cleu_Ara098-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-A09_Cleu_Ara099-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-A10_Cleu_Ara100-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-A11_Cleu_Dic063-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-A12_Cleu_Dic064-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-B01_Cleu_Dic065-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-B02_Cleu_Dic066-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-B03_Cleu_Dic068-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-B04_Cleu_Dic069-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-B05_Cleu_Dic070-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-B06_Cleu_Dic071-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-B07_Cleu_Dic072-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-B08_Cleu_Dic073-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-B09_Cleu_Mat029-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-B10_Cleu_Mat030-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-B11_Cleu_Mat031-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-B12_Cleu_Mat032-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-C01_Cleu_Mat033-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-C02_Cleu_Mat034-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-C03_Cleu_Mat035-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-C04_Cleu_Mat036-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-C05_Cleu_Mat037-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-C06_Cleu_Mat038-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-C07_Cleu_Mat018-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-C08_Cleu_Dic025-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-E01_Cleu_Sab040-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-E02_Cleu_Sab041-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-E03_Cleu_Sab042-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-E04_Cleu_Sab043-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-E05_Cleu_Sab044-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-E06_Cleu_Sab045-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-E07_Cleu_Sab046-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-E08_Cleu_Sab047-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-E09_Cleu_Sab048-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-E10_Cleu_Sab049-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-E11_Cleu_Ara076a-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-E12_Cleu_Ara077a-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-F01_Cleu_Ara080-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-F02_Cleu_Ara082-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-F03_Cleu_Ara085-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-F04_Cleu_Ara086-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-F05_Cleu_Ara087-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-F06_Cleu_Ara088-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-F07_Cleu_Ara089-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-F08_Cleu_Ara090-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-F09_Cleu_Dic050-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-F10_Cleu_Dic051-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-F11_Cleu_Dic052-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-F12_Cleu_Dic053-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-G01_Cleu_Dic054-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-G02_Cleu_Dic055-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-G03_Cleu_Dic056-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-G04_Cleu_Dic057-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-G05_Cleu_Dic058-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-G06_Cleu_Dic062-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-G07_Cleu_Dic018-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-2/CLE_2B-G08_Cleu_Mat023-RG.bam	>> data/SEQ/CLE2.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-A01_Cleu_Ara038-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-A02_Cleu_Ara039-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-A03_Cleu_Ara040-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-A04_Cleu_Ara041-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-A05_Cleu_Ara042-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-A06_Cleu_Ara043-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-A07_Cleu_Ara044-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-A08_Cleu_Ara045-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-A09_Cleu_Ara046-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-A10_Cleu_Ara047-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-A11_Cleu_Ara048-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-A12_Cleu_Ara049-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-B01_Cleu_Dic011-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-B02_Cleu_Dic012-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-B03_Cleu_Dic013-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-B04_Cleu_Dic014-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-B05_Cleu_Dic015-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-B06_Cleu_Dic016-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-B07_Cleu_Dic017-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-B08_Cleu_Dic018-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-B09_Cleu_Dic019-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-B10_Cleu_Dic020-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-B11_Cleu_Dic021-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-B12_Cleu_Dic022-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-C01_Cleu_Mat009-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-C02_Cleu_Mat010-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-C03_Cleu_Mat011-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-C04_Cleu_Mat012-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-C05_Cleu_Mat013-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-C06_Cleu_Mat014-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-C07_Cleu_Mat001-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-C08_Cleu_Ara082-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-E01_Cleu_Sab011-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-E02_Cleu_Sab012-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-E03_Cleu_Sab013-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-E04_Cleu_Sab014-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-E05_Cleu_Sab015-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-E06_Cleu_Sab016-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-E07_Cleu_Sab017-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-E08_Cleu_Sab018-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-E09_Cleu_Sab019-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-E10_Cleu_Sab020-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-E11_Cleu_Sab021-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-E12_Cleu_Sab022-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-F01_Cleu_Ara050-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-F02_Cleu_Ara051-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-F03_Cleu_Ara052-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-F04_Cleu_Ara053-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-F05_Cleu_Ara054-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-F06_Cleu_Ara055-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-F07_Cleu_Ara056-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-F08_Cleu_Ara057-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-F09_Cleu_Ara058-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-F10_Cleu_Ara059-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-F11_Cleu_Ara060-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-F12_Cleu_Ara061-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-G01_Cleu_Mat015-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-G02_Cleu_Mat016-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-G03_Cleu_Mat017-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-G04_Cleu_Mat018-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-G05_Cleu_Mat019-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-G06_Cleu_Mat020-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-G07_Cleu_Ara002-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3A-G08_Cleu_Mat030-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-A01_Cleu_Ara062-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-A02_Cleu_Ara063-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-A03_Cleu_Ara064-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-A04_Cleu_Ara065-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-A05_Cleu_Ara066-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-A06_Cleu_Ara067-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-A07_Cleu_Ara068-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-A08_Cleu_Ara069-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-A09_Cleu_Ara070-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-A10_Cleu_Ara071-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-A11_Cleu_Ara072-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-A12_Cleu_Ara073-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-B01_Cleu_Dic023-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-B02_Cleu_Dic024-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-B03_Cleu_Dic025-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-B04_Cleu_Dic026-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-B05_Cleu_Dic027-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-B06_Cleu_Dic028-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-B07_Cleu_Dic029-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-B08_Cleu_Dic030-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-B09_Cleu_Dic031-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-B10_Cleu_Dic032-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-B11_Cleu_Dic033-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-B12_Cleu_Dic034-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-C01_Cleu_Mat021-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-C02_Cleu_Mat022-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-C03_Cleu_Mat023-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-C04_Cleu_Mat024-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-C05_Cleu_Mat025-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-C06_Cleu_Mat026-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-C07_Cleu_San004-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-C08_Cleu_Dic070-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-E01_Cleu_Sab023-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-E02_Cleu_Sab024-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-E03_Cleu_Sab025-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-E04_Cleu_Sab026-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-E05_Cleu_Sab027-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-E06_Cleu_Sab028-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-E07_Cleu_Sab029-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-E08_Cleu_Sab030-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-E09_Cleu_Sab031-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-E10_Cleu_Sab032-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-E11_Cleu_Sab033-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-E12_Cleu_Sab034-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-F01_Cleu_Ara074-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-F02_Cleu_Ara075a-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-F03_Cleu_Dic035-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-F04_Cleu_Dic036-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-F05_Cleu_Dic038-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-F06_Cleu_Dic039-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-F07_Cleu_Dic040-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-F08_Cleu_Dic041-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-F09_Cleu_Dic042-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-F10_Cleu_Dic043-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-F11_Cleu_Dic044-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-F12_Cleu_Dic045-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-G01_Cleu_Dic046-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-G02_Cleu_Dic047-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-G03_Cleu_Dic048-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-G04_Cleu_Dic049-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-G05_Cleu_Mat027-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-G06_Cleu_Mat028-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-G07_Cleu_Dic019-RG.bam	>> data/SEQ/CLE3.flagstats
samtools flagstat	data/SEQ/CLE-3/CLE_3B-G08_Cleu_Dic049-RG.bam	>> data/SEQ/CLE3.flagstats
