cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_1
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_2
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_3
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_4
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_5
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_6
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_7
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_8
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_9
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_10
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_1
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_2
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_3
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_4
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_5
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_6
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_7
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_8
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_9
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_10
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_1
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_2
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_3
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_4
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_5
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_6
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_7
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_8
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_9
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_10
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_1
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_2
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_3
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_4
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_5
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_6
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_7
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_8
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_9
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_10
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_1
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_2
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_3
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_4
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_5
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_6
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_7
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_8
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_9
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_10
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_1
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_2
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_3
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_4
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_5
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_6
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_7
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_8
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_9
dDocent dDocent_maphiseq.config
cd /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_10
dDocent dDocent_maphiseq.config
