ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_1
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_2
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_3
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_4
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_5
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_6
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_7
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_8
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_9
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_10
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_1
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_2
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_3
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_4
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_5
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_6
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_7
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_8
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_9
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_10
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_1
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_2
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_3
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_4
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_5
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_6
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_7
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_8
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_9
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_10
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_1
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_2
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_3
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_4
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_5
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_6
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_7
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_8
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_9
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_10
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_1
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_2
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_3
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_4
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_5
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_6
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_7
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_8
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_9
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_10
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_1
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_2
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_3
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_4
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_5
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_6
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_7
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_8
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_9
ln -s /home/soleary/BULLSHARKS/CLE_POPGEN/data/SEQ/CLE-1/*.fq.gz /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_10
