mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_1
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_2
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_3
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_4
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_5
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_6
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_7
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_8
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_9
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_10
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_1
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_2
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_3
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_4
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_5
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_6
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_7
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_8
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_9
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_10
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_1
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_2
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_3
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_4
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_5
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_6
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_7
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_8
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_9
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_10
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_1
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_2
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_3
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_4
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_5
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_6
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_7
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_8
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_9
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_10
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_1
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_2
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_3
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_4
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_5
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_6
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_7
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_8
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_9
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_10
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_1
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_2
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_3
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_4
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_5
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_6
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_7
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_8
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_9
mkdir /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_10
