rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_1/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_2/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_3/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_4/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_5/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_6/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_7/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_8/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_9/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_10/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_1/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_2/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_3/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_4/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_5/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_6/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_7/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_8/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_9/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_10/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_1/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_2/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_3/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_4/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_5/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_6/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_7/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_8/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_9/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_10/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_1/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_2/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_3/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_4/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_5/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_6/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_7/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_8/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_9/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_10/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_1/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_2/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_3/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_4/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_5/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_6/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_7/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_8/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_9/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_10/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_1/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_2/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_3/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_4/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_5/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_6/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_7/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_8/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_9/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_10/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_1/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_2/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_3/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_4/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_5/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_6/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_7/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_8/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_9/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_10/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_1/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_2/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_3/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_4/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_5/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_6/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_7/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_8/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_9/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_10/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_1/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_2/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_3/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_4/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_5/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_6/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_7/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_8/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_9/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_10/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_1/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_2/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_3/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_4/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_5/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_6/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_7/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_8/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_9/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_10/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_1/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_2/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_3/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_4/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_5/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_6/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_7/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_8/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_9/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_10/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_1/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_2/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_3/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_4/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_5/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_6/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_7/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_8/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_9/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_10/*.seqs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_1/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_2/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_3/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_4/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_5/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_6/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_7/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_8/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_9/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_10/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_1/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_2/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_3/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_4/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_5/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_6/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_7/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_8/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_9/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_10/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_1/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_2/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_3/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_4/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_5/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_6/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_7/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_8/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_9/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_10/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_1/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_2/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_3/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_4/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_5/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_6/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_7/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_8/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_9/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_10/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_1/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_2/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_3/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_4/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_5/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_6/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_7/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_8/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_9/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_10/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_1/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_2/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_3/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_4/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_5/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_6/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_7/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_8/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_9/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_10/*.fastq
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_1/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_2/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_3/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_4/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_5/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_6/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_7/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_8/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_9/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_10/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_1/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_2/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_3/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_4/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_5/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_6/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_7/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_8/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_9/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_10/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_1/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_2/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_3/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_4/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_5/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_6/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_7/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_8/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_9/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_10/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_1/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_2/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_3/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_4/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_5/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_6/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_7/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_8/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_9/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_10/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_1/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_2/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_3/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_4/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_5/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_6/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_7/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_8/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_9/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_10/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_1/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_2/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_3/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_4/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_5/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_6/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_7/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_8/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_9/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_10/*.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_1/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_2/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_3/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_4/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_5/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_6/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_7/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_8/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_9/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_10/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_1/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_2/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_3/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_4/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_5/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_6/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_7/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_8/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_9/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_10/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_1/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_2/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_3/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_4/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_5/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_6/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_7/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_8/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_9/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_10/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_1/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_2/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_3/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_4/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_5/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_6/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_7/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_8/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_9/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_10/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_1/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_2/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_3/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_4/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_5/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_6/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_7/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_8/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_9/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_10/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_1/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_2/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_3/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_4/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_5/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_6/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_7/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_8/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_9/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_10/namelist
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_1/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_2/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_3/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_4/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_5/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_6/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_7/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_8/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_9/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_10/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_1/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_2/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_3/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_4/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_5/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_6/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_7/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_8/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_9/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_10/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_1/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_2/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_3/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_4/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_5/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_6/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_7/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_8/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_9/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_10/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_1/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_2/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_3/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_4/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_5/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_6/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_7/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_8/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_9/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_10/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_1/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_2/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_3/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_4/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_5/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_6/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_7/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_8/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_9/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_10/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_1/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_2/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_3/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_4/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_5/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_6/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_7/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_8/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_9/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_10/uniqCperindv
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_1/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_2/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_3/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_4/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_5/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_6/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_7/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_8/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_9/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_10/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_1/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_2/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_3/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_4/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_5/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_6/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_7/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_8/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_9/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_10/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_1/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_2/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_3/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_4/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_5/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_6/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_7/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_8/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_9/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_10/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_1/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_2/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_3/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_4/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_5/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_6/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_7/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_8/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_9/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_10/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_1/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_2/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_3/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_4/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_5/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_6/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_7/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_8/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_9/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_10/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_1/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_2/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_3/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_4/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_5/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_6/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_7/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_8/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_9/dDocent.runs
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_10/dDocent.runs
