rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_1/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_2/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_3/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_4/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_5/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_6/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_7/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_8/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_9/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF1_10/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_1/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_2/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_3/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_4/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_5/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_6/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_7/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_8/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_9/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF2_10/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_1/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_2/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_3/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_4/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_5/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_6/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_7/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_8/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_9/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF3_10/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_1/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_2/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_3/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_4/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_5/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_6/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_7/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_8/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_9/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF4_10/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_1/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_2/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_3/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_4/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_5/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_6/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_7/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_8/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_9/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF5_10/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_1/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_2/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_3/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_4/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_5/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_6/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_7/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_8/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_9/*.fq.gz
rm /home/soleary/BULLSHARKS/CLE_POPGEN/data/REF/REF6_10/*.fq.gz
