wd<-getwd()
source("src/dependencies.R")
source("src/changeExtension.R")
source("src/convertDatasets.R")
source("src/FSTcalcs.R")
source("src/FSTset.R")
source("src/getAllelesDataset.R")
source("src/getHeDataset.R")
source("src/getNumGens.R")
source("src/getPvalues.R")
source("src/getRunName.R")
source("src/getSampleSizeEachPop.R")
source("src/myexport.R")
source("src/sampleVarianceFST.R")
source("src/tictoc.R")
source("src/IMsims.R")
loadCFunctions.withDelete("src/")
setwd(wd)

#source("src/FODR_process.R")
#source("src/randomizeGenotypes.R")

